@startuml

title __XML's Class Diagram__\n

  namespace org.pneditor.save.xml {
    class org.pneditor.save.xml.DocumentExporter {
        + DocumentExporter()
        + getXmlPetriNet()
        + writeToFile()
        - getXmlArc()
        - getXmlPlace()
        - getXmlTransition()
    }
  }
  

  namespace org.pneditor.save.xml {
    class org.pneditor.save.xml.DocumentImporter {
        - nodeReferences : Map<Integer, GraphicNode>
        + readFromFile()
        - addNewArc()
        - addNewPlace()
        - addNewTransition()
        - getNewPetriNet()
        - getPetriNet()
    }
  }
  

  namespace org.pneditor.save.xml {
    class org.pneditor.save.xml.XmlArc {
        + breakPoints : List<XmlPoint>
        + destinationId : int
        + multiplicity : int
        + sourceId : int
        + type : String
    }
  }
  

  namespace org.pneditor.save.xml {
    class org.pneditor.save.xml.XmlDocument {
        + left : int
        + top : int
    }
  }
  

  namespace org.pneditor.save.xml {
    class org.pneditor.save.xml.XmlNode {
        + id : int
        + label : String
        + x : int
        + y : int
    }
  }
  

  namespace org.pneditor.save.xml {
    class org.pneditor.save.xml.XmlPetriNet {
        + arcs : List<XmlArc>
        + label : String
        + places : List<XmlPlace>
        + transitions : List<XmlTransition>
        + addArc()
        + addPlace()
        + addTransition()
    }
  }
  

  namespace org.pneditor.save.xml {
    class org.pneditor.save.xml.XmlPlace {
        + tokens : int
    }
  }
  

  namespace org.pneditor.save.xml {
    class org.pneditor.save.xml.XmlPoint {
        + x : int
        + y : int
    }
  }
  

  namespace org.pneditor.save.xml {
    class org.pneditor.save.xml.XmlTransition {
    }
  }
  

  org.pneditor.save.xml.DocumentExporter o-- org.pneditor.save.xml.XmlDocument : xmlDocument
  org.pneditor.save.xml.DocumentImporter o-- org.pneditor.save.xml.XmlDocument : xmlDocument
  org.pneditor.save.xml.XmlDocument o-- org.pneditor.save.xml.XmlPetriNet : petriNet
  org.pneditor.save.xml.XmlPlace -up-|> org.pneditor.save.xml.XmlNode
  org.pneditor.save.xml.XmlTransition -up-|> org.pneditor.save.xml.XmlNode


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
