@startuml

title __ENTITIES's Class Diagram__\n

  namespace filRouge.Entities {
    class filRouge.Entities.Arc {
        {static} - LOGGER : Logger
        - in : boolean
        - weight : int
        + Arc()
        + Arc()
        + getConnectedPlace()
        + getWeight()
        + isAvailable()
        + isIn()
        + setConnectedPlace()
        + setIn()
        + setWeight()
        + toString()
    }
  }
  

  namespace filRouge.Entities {
    class filRouge.Entities.Place {
        - tokens : int
        + Place()
        + Place()
        + addTokens()
        + deleteTokens()
        + getTokens()
        + setTokens()
    }
  }
  

  namespace filRouge.Entities {
    class filRouge.Entities.Transition {
        - available : boolean
        - inArcs : List<Arc>
        - outArcs : List<Arc>
        + Transition()
        + addInArc()
        + addOutArc()
        + getInArcs()
        + getOutArcs()
        + isAvailable()
        + setArcWeight()
        + setAvailable()
        + setInArcs()
        + setOutArcs()
    }
  }
  

  namespace filRouge.Entities {
    class filRouge.Entities.ViderArc {
        + ViderArc()
        + clearPlace()
        + isAvailable()
    }
  }
  

  namespace filRouge.Entities {
    class filRouge.Entities.ZeroArc {
        + ZeroArc()
        + isAvailable()
        + isPlaceVide()
    }
  }
  

  filRouge.Entities.Arc o-- filRouge.Entities.Place : connectedPlace
  filRouge.Entities.ViderArc -up-|> filRouge.Entities.Arc
  filRouge.Entities.ZeroArc -up-|> filRouge.Entities.Arc


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
